### ISSUE TITLE
add run method with basic authentication option

### ISSUE THREAD

**Issue by romanorac** [Spikeify/spikeify-cron#1]
add run method with basic authentication option to CronService interface.

**Comment by drejc** [comment]
Improved CronServiceImpl to utilize CronSettings where rootUrl, basic auth user and password can be specified.
DefaultCronSettings implements CronSettings as a setting holder.

Use as follows:

manager = new CronManagerImpl(sfy);
executor = new CronExecutorImpl();
settings = new DefaultCronSettings(...);
service = new CronServiceImpl(manager, executor, settings);
